# Generated by Django 5.1.6 on 2025-02-11 14:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trick',
            name='photo',
        ),
        migrations.AddField(
            model_name='trick',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AddField(
            model_name='trick',
            name='instructions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=[], size=None),
        ),
    ]
