# Generated by Django 5.1.6 on 2025-02-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0003_alter_trick_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrickTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tricks', models.ManyToManyField(to='tricks.trick')),
            ],
        ),
        migrations.AddField(
            model_name='trick',
            name='tags',
            field=models.ManyToManyField(to='tricks.tricktag'),
        ),
    ]
