# Generated by Django 5.1.6 on 2025-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0004_tricktag_trick_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='tags',
            field=models.ManyToManyField(related_name='tricks_trick_related', to='tricks.tricktag'),
        ),
        migrations.AlterField(
            model_name='tricktag',
            name='tricks',
            field=models.ManyToManyField(related_name='tricks_tricktag_related', to='tricks.trick'),
        ),
    ]
