# Generated by Django 5.1.6 on 2025-02-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0007_alter_tricktag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tricktag',
            name='tricks',
        ),
    ]
