# Generated by Django 5.1.6 on 2025-02-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0008_remove_tricktag_tricks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
