# Generated by Django 5.1.6 on 2025-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0009_alter_trick_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
