# Generated by Django 5.1.6 on 2025-02-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0010_trick_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tricks_trick_related', to='tricks.tricktag'),
        ),
    ]
